module.exports = {
    // Payload
    KERANJANG_BAYAR: "KERANJANG_BAYAR",
    KERANJANG_TAMBAH: "KERANJANG_TAMBAH",
    KERANJANG_HAPUS: "KERANJANG_HAPUS",
    KERANJANG_GET: "KERANJANG_GET",


    BARANG_GET: "BARANG_GET",
    BARANG_EDIT: "BARANG_EDIT",
    BARANG_HAPUS: "BARANG_HAPUS",
    BARANG_TAMBAH: "BARANG_TAMBAH",
    BARANG_UPDATE: "BARANG_UPDATE",

    TRANSAKSI_TAMBAH: "TRANSAKSI_TAMBAH",
    TRANSAKSI_GET: "TRANSAKSI_GET",
    TRANSAKSI_LAST_ID: "TRANSAKSI_LAST_ID",
    TRANSAKSI_CANCEL: "TRANSAKSI_CANCEL",
    TRANSAKSI_HAPUS: "TRANSAKSI_HAPUS",
    TRANSAKSI_BAYAR: "TRANSAKSI_BAYAR",

    TUTUP: "TUTUP",


    // Database
    DB: "src/resources/db/database.db",
}



